export const occupationData = [
  { occupation: "Engineering" },
  { occupation: "Design" },
  { occupation: "Management" },
  { occupation: "Data" },
  { occupation: "Education" },
  { occupation: "Healthcare" },
  { occupation: "Finance" },
  { occupation: "Marketing" },
  { occupation: "Technology" },
  { occupation: "Sales" },
  { occupation: "Human Resources" },
  { occupation: "Construction" },
  { occupation: "Consulting" },
  { occupation: "Legal" },
  { occupation: "Art & Media" },
  { occupation: "Customer Support" },
  { occupation: "Hospitality" },
  { occupation: "Retail" },
  { occupation: "Science" },
  { occupation: "Unemployed" },
];
